Repository QuiltMC/developer-wiki, pull requests merged in 2023-09, with the labels that each got.

#46 update modrinth licensing guide blogpost link
  wiki/versions/1.19/getting_started/setup/markdown/setup.md
Labels: Content

#52 [Rewrite] Wiki base structure
  package.json
  pnpm-lock.yaml
  src/lib/HtmlHead.svelte
  src/lib/types.d.ts
  src/routes/+layout.server.ts
  src/routes/[category]/[slug]/+page.svelte
  svelte.config.js
  wiki/blocks/+category.yml
  wiki/blocks/first-block.md
  wiki/blocks/oriented-block.md
  wiki/blocks/redstone-interaction.md
  wiki/concepts/+category.yml
  wiki/concepts/events.md
  wiki/concepts/libraries.md
  wiki/concepts/lifecycles-ticks.md
  wiki/concepts/minecraft-code-structure.md
  wiki/concepts/mixins.md
  wiki/concepts/nbt.md
  wiki/concepts/networking.md
  wiki/concepts/qsl-qfapi.md
  wiki/concepts/registries.md
  wiki/concepts/sideness.md
  wiki/data/+category.yml
  wiki/data/adding-recipes.md
  wiki/data/rea.md
  wiki/data/recipe-api.md
  wiki/data/recipe-type.md
  wiki/introduction/+category.yml
  wiki/introduction/get-started.md
  wiki/introduction/setting-up.md
  wiki/items/+category.yml
  wiki/items/armor.md
  wiki/items/first-item.md
  wiki/items/food.md
  wiki/items/tools.md
  wiki/misc/+category.yml
  wiki/misc/commands.md
Labels: enhancement, Content

#56 Add github actions & fix build errors
  .github/ISSUE_TEMPLATE/bug_report.yaml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/wiki-request.yaml
  .github/workflows/commit-preview.yaml
  .github/workflows/pr-preview-footer.yaml
  .github/workflows/pr-preview.yaml
  .github/workflows/publish-pr-preview.yaml
  wiki/items/first-item.md
Labels: enhancement
