Repository QuiltMC/developer-wiki, pull requests merged in 2024-04, with the labels that each got.

#96 Fix gh-88
  src/lib/HtmlHead.svelte
Labels: enhancement

#98 fix up intro category
  static/introduction/template-mod-intellij-dark.png
  static/introduction/template-mod-intellij-light.png
  wiki/introduction/get-started/en.md
  wiki/introduction/setting-up/en.md
Labels: page update, final comment period

#86 "Customizing your Mappings" article
  src/lib/translations/en/wiki.json
  wiki/misc/mappings/+page.yml
  wiki/misc/mappings/en.md
Labels: content, new page, final comment period

#94 Added links to the english version for easier navigation
  src/lib/NavbarLangDropdown.svelte
  src/lib/stores.ts
  src/lib/svelte-markdown/NoPreloadLink.svelte
  src/lib/translations/en/application.json
  src/lib/translations/en/wiki.json
  src/lib/translations/fr/application.json
  src/lib/translations/fr/wiki.json
  src/routes/+layout.svelte
  src/routes/[[locale=locale]]/[category]/[[slug]]/+page.svelte
  src/routes/[[locale=locale]]/[category]/[[slug]]/+page.ts
Labels: enhancement

#95 Actually render drafts at build time
  src/lib/Sidebar.svelte
  src/lib/types.d.ts
  src/routes/+layout.server.ts
Labels: enhancement
